services:
  - name: arm-voice-backend
    type: web          # not pserv
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    dockerCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

  - name: arm-voice-frontend
    type: web
    runtime: python
    plan: free
    region: frankfurt
    rootDir: .
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: python frontend/gradio_app.py
    envVars:
      - key: BACKEND_HOSTPORT
        fromService:
          name: arm-voice-backend
          type: web
          property: hostport
      - key: GRADIO_SERVER_NAME
        value: 0.0.0.0
