services:
  - name: arm-voice
    type: web
    plan: free
    region: frankfurt
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
